name: fixer
description: A framework to make large analysis options migrations easier
version: 0.1.1
homepage: https://github.com/IO-Design-Team/fixer

environment:
  sdk: ^3.0.0

dependencies:
  collection: ^1.17.2
  parselyzer: ^0.1.0

dev_dependencies:
  rexios_lints: ^15.0.0
  test: ^1.21.0
